name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install project dependencies
      run: |
        python -m poetry install
    - name: Check flake8
      run: |
        poetry run flake8 .
    - name: Check bandit
      run: |
        poetry run bandit {{cookiecutter.project_slug}}/*.py
    - name: run Pytest
      run: |
        poetry run pytest
        poetry run pytest -s --cov=trdl --cov-append --cov-report=xml --cov-report term-missing tests
