name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "gh_secret_docker_hub_token" | docker login --username "gh_secret_docker_hub_username" --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag gh_secret_docker_hub_username/${{ cookiecutter.project_slug }}:latest \
            --push .
